apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fission

patchesJson6902:
- target:
    version: v1
    kind: ServiceAccount
    name: fission-fetcher
  path: namespace-fission-function.yaml
- target:
    version: v1
    kind: ServiceAccount
    name: fission-builder
  path: namespace-fission-builder.yaml

patchesStrategicMerge:
  - istio_sidecar_injection_false.yaml

resources:
- namespace.yaml
- ../../generated/fission/fission-all.yaml
